### ISSUE TITLE
Full path is not being read

### ISSUE THREAD

**Issue by nitincoded** [nitincoded/backup_archiver#2]
On running:
`python backupArchiver.py --src=e:\TestScriptz-01\sorcerer --dest=e:\TestScriptz-01\destiny`

The output is:

```
Src: e
Dest: e
Traceback (most recent call last):
  File "backupArchiver.py", line 127, in <module>
    main(sys.argv)
  File "backupArchiver.py", line 124, in main
    process_args(sargv)
  File "backupArchiver.py", line 102, in process_args
    copy_files(src_loc, dest_loc, list_for_copy(src_loc, dest_loc))
  File "backupArchiver.py", line 39, in list_for_copy
    src_child_files_and_dirs = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'e'
```

Only the first character of the src and dest arguments are being read.

**Comment by nitincoded** [comment]
Found the bug: Problem was a "arr[index]" instead of "arr[index**:**]"

**Comment by nitincoded** [comment]
Change committed

https://github.com/nitincoded/backup_archiver/commit/73835db2299781da8352d05fb0015f2d23e84b97#diff-84e48da60d6424c4d1855d2f011550a5
